#!/bin/sh
# Writes /usr/share/nginx/html/config.js so the frontend JS knows where the API is.
# Set API_URL env var when running the container; defaults to same-host /api proxy.
set -e

API_URL="${API_URL:-}"   # empty = use Nginx proxy (recommended for Docker)

cat > /usr/share/nginx/html/config.js <<EOF
// Auto-generated by docker-entrypoint.sh — do not edit manually
window.WILDLOG_API = '${API_URL}';
EOF

echo "[wildlog] config.js written — WILDLOG_API='${API_URL}'"

# Hand off to Nginx
exec nginx -g 'daemon off;'
